baseURL: 'https://lobovit.github.io/'
locale: 'pt-br'
title: 'lobovit'
theme: 'lobovit'
publishDir: '..'

params:
  author: Vitor Lobo
  email: lobocode@gmail.com
  github: https://github.com/lobovit
  linkedin: https://linkedin.com/in/vitor-lobo
  description: engenharia de software, compiladores, sistemas e programacao

menu:
  main:
    - identifier: about
      name: about
      url: /page/about/
      weight: 1
    - identifier: contact
      name: contact
      url: /page/contact/
      weight: 2

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
  tableOfContents:
    startLevel: 2
    endLevel: 4

taxonomies:
  tag: tags

permalinks:
  post: /:contentbasename/
