+++
title = "Sobre"
description = "Vitor Lobo — desenvolvedor, open source, infraestrutura e compiladores"
date = 2025-07-28
weight = 1
+++

Olá, eu sou *Vitor Lobo*, ou simplesmente Lobo.

Sou desenvolvedor com mais de 15 anos de experiência e já passei por infraestrutura, engenharia de plataforma e SRE. Mas é no código que me encontro: construir soluções e entregar valor, seja corporativo ou social, é o que me move. Comecei em 2009 nas comunidades open source do IRC (falecida freenode). Foi ali que aprendi sobre colaboração, compartilhamento e a cultura do software livre e open source. Mantenho este blog para compartilhar descobertas, aprendizados e conhecimento em geral.

* Projetos

** Go

- [[https://github.com/scovl/ollanta][Ollanta]], análise estática multi-linguagem
- [[https://github.com/scovl/saitama][Saitama]], graceful shutdown para processos Unix
- [[https://github.com/scovl/gopherlab][GopherLab]], laboratório de experimentos em Go

** Clojure

- [[https://github.com/scovl/dogai][Dogai]], detecção de objetos em vídeo com redes neurais
- [[https://github.com/scovl/docai][Docai]], assistente RAG para documentação técnica
- [[https://github.com/scovl/pomodoro][Pomodoro]], técnica Pomodoro integrada ao Emacs

** C / Rust

- [[https://github.com/scovl/checkrc][Checkrc]], validador de configurações para FreeBSD
- [[https://github.com/rochacbruno/marmite][Marmite]], contribuições para este gerador de sites estáticos em Rust

** Contribuições open source

- [[https://github.com/SpectoLabs/hoverfly][Hoverfly]], simulação e mock de APIs
- [[https://github.com/spf13/cobra][Cobra]], biblioteca de CLI em Go
- [[https://github.com/elazarl/goproxy][Go Proxy]], proxy HTTP/HTTPS em Go

Fora do código, gosto de escrever, estudar filosofia e literatura, e coleciono livros da editora DarkSide.
